Algoritmo "Fahrenheit para Celsius"
// Disciplina   : [Linguagem e Logica de Programacao em JavaScript]
// Professor   : Jailson
// Descricao   : Fahrenheit para Celsius
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 15/04/2024
Var
grausF, conversao: real

Inicio
Escreva("Digite a temperatura em Fahrenheit: ")
Leia(grausF)

conversao <- (grausF - 32) / 1.8
Escreva("Em Celsius fica: ", conversao)

Fimalgoritmo