Algoritmo "Celsius para Fahrenheit"
// Disciplina   : [Linguagem e Logica de Programacao em JavaScript]
// Professor   : Jailson
// Descricao   : Celsius para Fahrenheit
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 15/04/2024
Var
grausC, conversao: real

Inicio
Escreva("Digite a temperatura em Celsius: ")
Leia(grausC)

conversao <- (9 * grausC + 160) / 5
Escreva("Em Fahrenheit fica: ", conversao)

Fimalgoritmo