Algoritmo "Exercicio5D"
// Disciplina   : [Linguagem e Logica de Programacao com JS]
// Professor   : Jailson
// Descricao   : Impares de 0 a 20
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 11/04/2024
Var
   count: inteiro

Inicio

   Enquanto count <= 20 faca
      Se count % 2 = 1 entao
         Escreval(count, " e Impar")
      FimSe
      count<- count + 1
   FimEnquanto

Fimalgoritmo