Algoritmo "Exercicio5B"
// Disciplina   : [Linguagem e Logica de Programacao com JavaScript]
// Professor   : Jailson
// Descricao   : Soma dos cem primeiros numeros
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 12/04/2024
Var
   count, soma: inteiro

Inicio

   Enquanto count <= 100 faca
      soma <- soma + count
      count<- count + 1
   FimEnquanto
   
   Escreval("A soma de todos os cem primeiros numeros e: ", soma)

Fimalgoritmo