Algoritmo "Exercicios1C"
// Disciplina   : [Linguagem e Logica de Programacao com JS]
// Professor   : Jailson
// Descricao   : Soma dos numeros de 1 a 100
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 13/04/2024
Var
   count, somados: inteiro

Inicio
   para count de 1 ate 100 passo 1 faca
      somados <- somados + count
   FimPara

   Escreva("O Somatorio dos numeros de 1 a 100: ", somados)

Fimalgoritmo