Algoritmo "Exercicios1F"
// Disciplina   : [Linguagem e Logica de Programacao com JavaScript]
// Professor   : Jailson
// Descricao   : Divisiveis por 4
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 13/04/2024
Var
   count: inteiro

Inicio
   para count de 1 ate 200 passo 1 faca
      Se count % 4 = 0 entao
         Escreval("O numero", count, " e divisivel por 4.")
      FimSe
   FimPara

Fimalgoritmo