Algoritmo "Exercicios1E"
// Disciplina   : [Linguagem e Logica de Programacao com JavaScript]
// Professor   : Jailson
// Descricao   : Impares de 0 a 20
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 13/04/2024
Var
   count: inteiro

Inicio
   para count de 0 ate 20 passo 1 faca
      Se count % 2 = 1 entao
         Escreval("O numero", count, " e Impar.")
      FimSe
   FimPara

Fimalgoritmo