Algoritmo "Exercicios1J"
// Disciplina   : [Linguagem e Logica de Programacao com JavaScript]
// Professor   : Jailson
// Descricao   : Graus Celsius em Fahrenheit
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 13/04/2024
Var
   gCelsius: inteiro
   gFahren: real

Inicio
   para gCelsius de 0 ate 100 passo 10 faca
      gFahren <- (9 * gCelsius + 160) / 5
      Escreval(gCelsius,"gC em Graus Fh: ", gFahren)
   FimPara

Fimalgoritmo