Algoritmo "Exercicio4I"
// Disciplina   : [Linguagem e Logica de Programacao em JS]
// Professor   : Jailson
// Descricao   : Valor par ou impar
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 15/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(num)

   Se num % 2 = 0 entao
      Escreva("O valor e par")
   Senao
      Escreva("O valor e impar")
   FimSe

Fimalgoritmo