Algoritmo "Exercicio4K"
// Disciplina   : [Linguagem e Logica de Programacao em JS]
// Professor   : Jailson
// Descricao   : Numero menor que 3
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 15/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor (menor que 3): ")
   Leia(num)

   Se num > 3 entao
      Escreva("Numero maior que 3!")
   Senao
      Escreva("Numero e: ", num)
   FimSe

Fimalgoritmo