Algoritmo "Exercicio4J"
// Disciplina   : [Linguagem e Logica de Programacao em JS]
// Professor   : Jailson
// Descricao   : Dentro ou fora do intervalo
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 15/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor (de 1 a 9): ")
   Leia(num)

   Se (num < 1) OU (num > 9) entao
      Escreva("Numero fora do intervalo permitido")
   Senao
      Escreva("Numero dentro do intervalo permitido")
   FimSe

Fimalgoritmo