Algoritmo "ExercicioARepita"
// Disciplina   : [Linguagem e Logica de Programacao com JavaScript]
// Professor   : Jailson
// Descricao   : Apresentar os quadrados dos numeros inteiros de 15 a 200.
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 12/04/2024
Var
   contadora: inteiro

Inicio
   contadora <- 15
   Repita
      Escreval("O numero", contadora, " ao quadrado e: ", contadora ^ 2)
      contadora <- contadora + 1
   Ate contadora > 200


Fimalgoritmo