Algoritmo "Numero positivo"
// Disciplina   : [Linguagem e Logica de Programacao em JavaScript]
// Professor   : Jailson
// Descricao   : Verifique se o numero e positivo ou negativo
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 12/04/2024
Var
   num: inteiro

Inicio
   Escreval("Escreva um numero: ")
   Leia(num)
   Se (num >= 0) entao
      Escreval("e positivo")
   Senao
      Escreval("e negativo")
   Fimse


Fimalgoritmo