Algoritmo "Converter Fahrenheit em Celsius"
// Disciplina   : [Linguagem e Logica de Programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descricao   : Converter Fahrenheit em Celsius
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 13/04/2024
Var

grausF, conversao: real

Inicio
Escreval("Digite a temperatura em Fahrenheit: ")
Leia(grausF)
conversao <- (grausF - 32) / 1.8
Escreval("A temperatura em Celsius e: ", conversao)


Fimalgoritmo