Algoritmo "Maior que 10"
// Disciplina   : [Linguagem e Logica de Programacao em JavaScript]
// Professor   : Jailson
// Descricao   : Verifique se o numero e maior que 10
// Autor(a)    : Daniel Marques Coutinho
// Data atual  : 12/04/2024
Var
   num: inteiro

Inicio
   Escreval("Escreva um numero: ")
   Leia(num)
   Se (num > 10) entao
      Escreval("e maior que 10!")
   Senao
      Escreval("Nao e menor que 10!")
   Fimse


Fimalgoritmo